apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwOi8vc2VhbG9zLmh1Yjo1MDAwLyI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJwYXNzdzByZCIsImF1dGgiOiJZV1J0YVc0NmNHRnpjM2N3Y21RPSJ9fX0=
kind: Secret
metadata:
  name: {{ include "registry-proxy.fullname" . }}
  labels:
    {{- include "registry-proxy.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
