apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry-proxy.fullname" . }}
  labels:
    {{- include "registry-proxy.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" .Values.registry.address .Values.registry.auth | b64enc }}
